language: python
python:
  - "2.7"
  - "3.6"
virtualenv:
  system_site_packages: true
sudo: required
dist: bionic
services:
  - xvfb
addons:
  apt:
    sources:
      - sourceline: 'deb http://us-east-1.ec2.archive.ubuntu.com/ubuntu/ bionic universe multiverse'
    update: true
before_install:
  - if [[ $TRAVIS_PYTHON_VERSION < 3 ]]; then
    sudo apt install -y python-gtk2;
    else
    wget http://mirrors.kernel.org/ubuntu/pool/main/p/pygobject/python3-gi_3.30.1-1ubuntu1_amd64.deb;
    sudo dpkg -i python3-gi_3.30.1-1ubuntu1_amd64.deb;
    wget http://mirrors.kernel.org/ubuntu/pool/main/p/pygobject/python3-gi-cairo_3.30.1-1ubuntu1_amd64.deb;
    sudo dpkg -i python3-gi-cairo_3.30.1-1ubuntu1_amd64.deb;
    wget http://mirrors.kernel.org/ubuntu/pool/main/g/gtk+3.0/gir1.2-gtk-3.0_3.24.1-1ubuntu2_amd64.deb;
    sudo dpkg -i gir1.2-gtk-3.0_3.24.1-1ubuntu2_amd64.deb;
    sudo apt-get install libgirepository1.0-dev;
    fi
install:
  - pip install -r requirements-dev.txt
script:
  - python atest/run.py -e no-xvfb atest;
